### PR TITLE
added walking and attacking sfx

### PR DESCRIPTION
**Pull request by beibarys98**
gitignore does not seem to work. i tried some things, but unsuccessful.

### CODE REVIEW

**Comment by Grimmys** [comment]
Very interesting sound effects and background music, you did a great job, thanks!

I will try to remove the useless files (venv + ipynb_checkpoints).

I'm also not a big fan of the comments you added before your statements, I don't think it's really useful and maintenable... (git keeps track of ownership of each contributor through access to commit history) 
So if you agree I will probably remove them too, and I will add a line in the CREDITS file to precise that sound effects and their integration into the game have been made by you! 
(However, if you took sound effects from some open source project it's ok too, I would just like to know who should be credited)

**Comment by beibarys98** [comment]
sound effects are from random places of the internet. youtube, websites. but one person who deserves credit is soundtrack composer. i took it from youtube and converted it to 8 bit music. it holds no copyright, so it is free. Kevin Macleod made it. https://www.youtube.com/user/kmmusic

**Comment by Grimmys** [comment]
Nice thanks!

Do you still have the direct link to the original soundtrack please ?
It's just to made a proper attribution to the artist, if you don't have it it's ok.

**Comment by beibarys98** [comment]
https://www.youtube.com/watch?v=eZ_r1H9vHkI&ab_channel=AlwaysMusic

this is the music

**Pull request merged**
