### PR TITLE
created pizza.txt

### PR DESCRIPTION
**Pull request by Akidur-Rahman**

### CODE REVIEW

**Comment by pycoinfu** [comment]
L pr

**Comment by pycoinfu** [comment]
W pizza recipe tho

**Comment by Grimmys** [comment]
Hello @Akidur-Rahman,

Congrats on making your first PR, looks like it has been created without any issue, lol.
Since obviously I'm not going to merge it, could you please close it?
I could do it myself, but might be the good occasion for you to try it for the first time as well. 🙂

**Comment by Akidur-Rahman** [comment]
After Doing some Google search i have finally figured out how to close it !!! 😌

**Pull request closed without merging**
