### PR TITLE
Replace the sprites

### PR DESCRIPTION
**Pull request by Danix421**
Hi, i'm Danix, a developer that love Python and games! Sorry if my english is bad but i only speak spanish. I viewed the RPG Tactical Fantasy Game, and why i'm looking to contribute to other people projects, i want to contribute to this game. For my contribution, i want to totally replace the game sprites, why they looks like the game was created with a visual app for create games like RPG Maker and the people is not looking for game like that. The sprites are not created for now, why i need to know if i can do it, so.. i need that this game creator give me permission to do it. I already changed the README's game version to 2.0.0, why this update is not little and is that for why i am looking for the permission of the game creator. Well, i hope he accept it.

### CODE REVIEW

**Comment by Danix421** [comment]
Oh, sorry but i can do the sprites, i have some things that i need to do. Sorry again!

**Comment by Grimmys** [comment]
Hi @Danix421, thank you for your interest in my game. :)

In fact the game sprites are taken straight from this tileset : https://opengameart.org/content/dungeon-crawl-32x32-tiles-supplemental
I like them because I would like to make a " retro " RPG Turn-based game (inspired by Fire Emblem, Final Fantasy Tactics and other old games), even if the tiles for the mapping are not really suitable to my project. But I'm open to any suggestion!

According to your last comment, I assume you've changed your mind, but I've decided to give you an answer to clear up things.

**Comment by Danix421** [comment]
> Hi @Danix421, thank you for your interest in my game. :)
> 
> In fact the game sprites are taken straight from this tileset : https://opengameart.org/content/dungeon-crawl-32x32-tiles-supplemental
> I like them because I would like to make a " retro " RPG Turn-based game (inspired by Fire Emblem, Final Fantasy Tactics and other old games), even if the tiles for the mapping are not really suitable to my project. But I'm open to any suggestion!
> 
> According to your last comment, I assume you've changed your mind, but I've decided to give you an answer to clear up things.

Thanks, Grimmys. If you, in a near future, create a new game, please, contact me on my GitHub profile, i wan't to make games like you!

**Comment by Grimmys** [comment]
I don't think I will create a new game in Python/Pygame in a near future, maybe a small game for a gamejam though.
Anyway, I will think about it, and don't hesitate to contact me too if you want to try to make your own game.

**Comment by Danix421** [comment]
> I don't think I will create a new game in Python/Pygame in a near future, maybe a small game for a gamejam though.
> Anyway, I will think about it, and don't hesitate to contact me too if you want to try to make your own game.

Ok, thanks!

**Pull request closed without merging**
