### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by SimonMaracine**
.gitignore was mandatory, because it was not possible to `git add .` without also adding some
unwanted files and folders. And maybe 

- build/
- InTheNameOfTheFive_v0_0_4.zip

should probably be ignored too, as they are not part of the project, they are not source code or data.

### CODE REVIEW

**Comment by Grimmys** [comment]
Thank you for the cleaning and the .gitignore.
However, I don't know if **build/** and **InTheNameOfTheFive_v0_0_4.zip** should be ignored because I would like to give access to the game to people that don't have Python installed, to gather more opinions. I know, it's not the best way to do this, but it's a simple one. But yeah at least **build/** could be ignored, it's a lot of files...

**Comment by SimonMaracine** [comment]
> Thank you for the cleaning and the .gitignore.
> However, I don't know if **build/** and **InTheNameOfTheFive_v0_0_4.zip** should be ignored because I would like to give access to the game to people that don't have Python installed, to gather more opinions. I know, it's not the best way to do this, but it's a simple one. But yeah at least **build/** could be ignored, it's a lot of files...

Yes. You're right that we should offer binaries to people who don't have Python, but those binaries
are usually placed alongside the releases, not in the repository itself. People can easily go to the
**releases** section and download anything they want from there. Right now only the source code
can be downloaded (zip or tar.gz), but you can still edit those releases and add binaries, if you want
to. It's ok anyway.

**Comment by Grimmys** [comment]
Oh yeah, you're right. I'm sorry, it's my first real " " big " " project. I added binaries to my releases, and I will update .gitignore during my next commit. Thank you again. ;)

**Comment by SimonMaracine** [comment]
> Oh yeah, you're right. I'm sorry, it's my first real " " big " " project. I added binaries to my releases, and I will update .gitignore during my next commit. Thank you again. ;)

You don't need to thank me. I'm just trying too help out where I can.

**Pull request merged**
